name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2025, macos-15]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-2025
            platform: win
          - os: macos-15
            platform: mac
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Setup JavaFX dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Rename artifact
      run: |
        cd target
        mv liftup-*.jar "liftup-${{ matrix.platform }}.jar"
      shell: bash
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: liftup-${{ matrix.platform }}
        path: target/liftup-${{ matrix.platform }}.jar
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Display structure of downloaded files
      run: ls -R artifacts/
        
    - name: Prepare Release Files
      run: |
        mkdir release-files
        cp artifacts/liftup-linux/liftup-linux.jar release-files/
        cp artifacts/liftup-win/liftup-win.jar release-files/
        cp artifacts/liftup-mac/liftup-mac.jar release-files/
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release-files/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generateReleaseNotes: true
        allowUpdates: true
        replacesArtifacts: true
