name: CI

on:
	push:
		branches: [ main ]
	pull_request:
		branches: [ main ]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
				uses: actions/checkout@v4

			- name: Cache Maven local repository
				uses: actions/cache@v4
				with:
					path: ~/.m2/repository
					key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

			- name: Set up JDK 21
				uses: actions/setup-java@v4
				with:
					distribution: 'temurin'
					java-version: '21'

			- name: Build with Maven
				run: mvn -B -V -DskipTests=false package --file pom.xml

			- name: List target
				run: ls -la target || true

			- name: Upload built JAR as workflow artifact
				uses: actions/upload-artifact@v4
				with:
					name: liftup-jar
					path: target/*.jar
