name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Setup JavaFX dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Rename artifact
      run: |
        cd target
        mv liftup-*.jar "liftup-${{ matrix.platform }}.jar"
      shell: bash
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: liftup-${{ matrix.platform }}
        path: target/liftup-${{ matrix.platform }}.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          liftup-linux/liftup-linux.jar
          liftup-win/liftup-win.jar
          liftup-mac/liftup-mac.jar
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
